name: build-keydb-container

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  KEYDB_REPO: "https://github.com/Snapchat/KeyDB"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set current repo release tag  # TODO: maybe we should figure out SRC_REPO release tag from given tag?
        run: echo "GH_REPO_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Determine latest keydb tag
        run: |
          echo "LATEST_TAG=$(git ls-remote --tags --exit-code --refs "$KEYDB_REPO" | sed -E 's/^[[:xdigit:]]+[[:space:]]+refs\/tags\/(.+)/\1/g' | tail -n1)" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@f19c3691d56f26e3f97547999df66a9ecbf0d9b0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          #            type=raw,value=latest
          tags: |
            type=semver,pattern={{version}},value=${{ env.LATEST_TAG }}
            type=raw,value=${{ env.GH_REPO_TAG }}

      - name: Build and Push Container Image(s)
        uses: docker/build-push-action@v4
        with:
          context:
          platforms: linux/amd64  # ,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SRC_REPO=${{ env.KEYDB_REPO }}
            BRANCH=${{ env.LATEST_TAG }}
